# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ttime < Formula
  desc "Local heartbeat daemon client for ttime.ai"
  homepage "https://ttime.ai"
  version "0.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tokentimeai/client/releases/download/v0.1.9/ttime_Darwin_x86_64.tar.gz"
      sha256 "e7bb23c672f49e415d60ac8144f8c2de4bef36a00e8f2e73cd81f6e94f887b88"

      define_method(:install) do
        bin.install "ttime"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tokentimeai/client/releases/download/v0.1.9/ttime_Darwin_arm64.tar.gz"
      sha256 "a8c02fc5ac1657b1fa35c3fcd172975014225ebe4ecaac5f999404f891af6206"

      define_method(:install) do
        bin.install "ttime"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tokentimeai/client/releases/download/v0.1.9/ttime_Linux_x86_64.tar.gz"
      sha256 "cd55ecc31f033497a717897f63871952d8dd8c824f8f5998536c6d893190b4f2"
      define_method(:install) do
        bin.install "ttime"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tokentimeai/client/releases/download/v0.1.9/ttime_Linux_arm64.tar.gz"
      sha256 "e3c61f4dd1b1f4d003b55ed74425a0411f7dd243113d2538ab9a987389a2fe33"
      define_method(:install) do
        bin.install "ttime"
      end
    end
  end

  service do
    run [opt_bin/"ttime", "daemon"]
    keep_alive true
    working_dir var
  end

  test do
    system "#{bin}/ttime", "help"
  end
end
