# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ttime < Formula
  desc "Local heartbeat daemon client for ttime.ai"
  homepage "https://ttime.ai"
  version "0.1.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tokentimeai/client/releases/download/v0.1.10/ttime_Darwin_x86_64.tar.gz"
      sha256 "dfc6377a101146adbd65f6705fc4755ee27ed521c1e88673b7437aaf5f1ab885"

      define_method(:install) do
        bin.install "ttime"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tokentimeai/client/releases/download/v0.1.10/ttime_Darwin_arm64.tar.gz"
      sha256 "011c60315b291ec0dd37d631c37ee5fd851a2feb832d6559b7f7ae26ef44c19f"

      define_method(:install) do
        bin.install "ttime"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tokentimeai/client/releases/download/v0.1.10/ttime_Linux_x86_64.tar.gz"
      sha256 "44b1dff3efa5b48a4ebd508cdf6f08fb9ec1457fab7e66f76989d48290603ed7"
      define_method(:install) do
        bin.install "ttime"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tokentimeai/client/releases/download/v0.1.10/ttime_Linux_arm64.tar.gz"
      sha256 "c776ea0c026deb27f3b80cb2b0c4323755630813f546ebb44ebb6061f7a69dc9"
      define_method(:install) do
        bin.install "ttime"
      end
    end
  end

  service do
    run [opt_bin/"ttime", "daemon"]
    keep_alive true
    working_dir var
  end

  test do
    system "#{bin}/ttime", "help"
  end
end
