# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ttime < Formula
  desc "Local heartbeat daemon client for ttime.ai"
  homepage "https://ttime.ai"
  version "0.1.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tokentimeai/client/releases/download/v0.1.12/ttime_Darwin_x86_64.tar.gz"
      sha256 "d4d7b41d25f0457e2dc20288e3d7acdedc458f6b3f82b458d08c709e2997b562"

      define_method(:install) do
        bin.install "ttime"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tokentimeai/client/releases/download/v0.1.12/ttime_Darwin_arm64.tar.gz"
      sha256 "e9e78e0ae52e93b5de5357e4ae24b3503ec549960d5cf2cd38ea5cd71ac7339a"

      define_method(:install) do
        bin.install "ttime"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tokentimeai/client/releases/download/v0.1.12/ttime_Linux_x86_64.tar.gz"
      sha256 "c9937041a1c33dba131536bda8cf5232c9c2be8b2d8636b4049d0082c8cb3535"
      define_method(:install) do
        bin.install "ttime"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tokentimeai/client/releases/download/v0.1.12/ttime_Linux_arm64.tar.gz"
      sha256 "5c2353646fad2b9cf7abce6622fff89c215a62642c3440b7b11211cd28160c6d"
      define_method(:install) do
        bin.install "ttime"
      end
    end
  end

  service do
    run [opt_bin/"ttime", "daemon"]
    keep_alive true
    working_dir var
  end

  test do
    system "#{bin}/ttime", "help"
  end
end
